[build]
  full_bin = "$HOME/go/bin/dlv --listen=127.0.0.1:44544 --headless --accept-multiclient exec ./ki365"
  pre_cmd = ["pkill ki365 || true"]
  cmd = "go build -gcflags='all=-N -l' -o ./ki365 ./server/"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "mjs"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
