services:
  ki365:
    container_name: ki365
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    image: ghcr.io/ki365/ki365:latest
  ki365-git:
    container_name: ki365-git
    build:
      dockerfile: ./docker/Dockerfile.git