services:
  git:
    container_name: git
    build:
      dockerfile: ./docker/Dockerfile.git
    profiles: [bin]
  kicad:
    container_name: kicad
    build:
      dockerfile: ./docker/Dockerfile.kicad
    environment:
      KI365_KICAD_PASSWORD: ${KI365_KICAD_PASSWORD}
    ports:
      - "22"
  gltfpack:
    container_name: gltfpack
    build:
      dockerfile: ./docker/Dockerfile.gltfpack
    profiles: [bin]
  # TODO: see note in corresponding dockerfile
  tracespace:
    container_name: tracespace
    build:
      dockerfile: ./docker/Dockerfile.tracespace
    environment:
      KI365_TRACESPACE_PASSWORD: ${KI365_TRACESPACE_PASSWORD}
  # NOTE: This image needs to be last as it depends on the above images to be built
  ki365:
    container_name: ki365
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    image: ghcr.io/ki365/ki365:latest
