services:
  ki365:
    container_name: ki365
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    image: ghcr.io/ki365/ki365:latest
  git:
    container_name: git
    build:
      dockerfile: ./docker/Dockerfile.git
  kicad:
    container_name: kicad
    build:
      dockerfile: ./docker/Dockerfile.kicad
    environment:
      KI365_KICAD_PASSWORD: ${KI365_KICAD_PASSWORD}
    ports:
      - "22"
  gltfpack:
    container_name: gltfpack
    build:
      dockerfile: ./docker/Dockerfile.gltfpack
