version: '3'

tasks:
  check-deps:
    desc: Checks all dependencies are installed
    cmds:
      - task --version
      - go version

  dev:
    desc: Runs the development server
    cmds:
      - task dev-frontend &
      - go run ./server/

  dev-frontend:
    desc: Runs the development frontend
    dir: './frontend'
    cmds: 
      - yarn
      - yarn dev

  dev-backend:
    desc: Runs the development backend
    cmds: 
      - go run ./server/

  build-frontend:
    desc: builds the frontend for production
    dir: './frontend'
    cmds:
      - yarn build 

  build-server:
    desc: Builds the server for production
    cmds:
      - go build -o ki365 -ldflags="-s -w" -trimpath ./server/ 