version: '3'

tasks:
  check:
    desc: Checks all dependencies are installed
    cmds:
      - task --version
      - go version
      - docker --version
      - yarn --version

  dev:
    desc: Runs the development server
    cmds:
      - task dev-frontend &
      - go run ./server/

  setup-examples:
    - git submodule update --init --progress
    - git clone --bare
    - go run ./scripts/examples.go

  dev-frontend:
    desc: Runs the development frontend
    dir: './frontend'
    cmds: 
      - yarn
      - yarn dev

  dev-backend-api:
    desc: Runs the development backend (api)
    cmds: 
      - go run ./server/

  dev-backend-kicad:
    desc: Runs the development backend (kicad)
    cmds:
      - docker compose run kicad

  build-frontend:
    desc: builds the frontend for production
    dir: './frontend'
    cmds:
      - yarn build 

  build-server:
    desc: Builds the server for production
    cmds:
      - go build -o ki365 -ldflags="-s -w" -trimpath ./server/ 

  build-git:
    desc: Build the static git binary dependency
    dir: './bin'
    cmds:
      - docker compose build git
      - docker rm tc || true
      - docker cp $(docker create --name tc ki365-git:latest --sleep 10):/libexec/git-core/git-http-backend . && docker rm tc
      - docker cp $(docker create --name tc ki365-git:latest --sleep 10):/libexec/git-core/git-http-backend.dbg . && docker rm tc
      # NOTE: To verify version uncomment this line and run ./bin/git --version
      # - docker cp $(docker create --name tc ki365-ki365-git:latest --sleep 10):/bin/git . && docker rm tc
  build-gltfpack:
    desc: Build and copy the gltfpack dependency
    dir: './bin'
    cmds:
      - docker compose build gltfpack
      - docker rm tc || true
      - docker cp $(docker create --name tc ki365-gltfpack:latest --sleep 10):/gltfpack . && docker rm tc
      - docker cp $(docker create --name tc ki365-gltfpack:latest --sleep 10):/gltfpack.dbg . && docker rm tc
  copy-bin:
    desc: Builds and copies executables from utility docker images for development
    dir: '.'
    deps: [build-git, build-gltfpack]
